### PR TITLE
Vbf analyzer nov02

### PR DESCRIPTION
**Pull request by nadjieh**
Fake rate part is fixed (should be checked explicitly by running the whole FR estimate machinery)
The code is compiled and running

### CODE REVIEW

**Comment by pfs** [comment]
@nadjieh @nshafiei 
I ran the SEL step last night the plots i get with the current version look good in general
http://psilva.web.cern.ch/psilva/VBFVectorBoson/3129835/nomvatree/plots/
i also updated this morning git with the NLO/LO transfer factors for the latest DY LO (HT binned samples)

**Comment by nadjieh** [comment]
@pfs 
so this is including my changes, right?

I ran also but have not yet checked the plots. I will go directly for the BDT re-training then

**Comment by nshafiei** [comment]
Hi,
Thanks Pedro,
I have run it too and i am going for comparison for 2017F.
Cheers
Negin

**Comment by pfs** [comment]
yes this includes changes from you @nadjieh

**Pull request merged**
